# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [54]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [55]:
# load csv file
file = pd.read_csv("../output_data/WeatherPy.csv")

# create a dataframe with the csv file
cities_df = pd.DataFrame(file)
cities_df.head()

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,Christchurch,-43.53,172.63,52.00,76,52,8.05,NZ,1607708120
1,Aksha,50.28,113.29,-2.69,86,4,4.45,RU,1607708186
2,Mandalgovi,45.76,106.27,-2.09,87,100,5.26,MN,1607708187
3,Saskylakh,71.92,114.08,-27.27,84,100,5.97,RU,1607708188
4,Tuktoyaktuk,69.45,-133.04,-22.00,74,20,8.05,CA,1607708189

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [56]:
# configure gmaps
gmaps.configure(api_key=g_key)

In [57]:
# create locations variable
locations = cities_df[["Lat", "Lng"]]

# create humidity variable
humidity = cities_df["Humidity"]

In [59]:
# plot heatmap
fig = gmaps.figure()

heat_layer = gmaps.heatmap_layer(locations, weights=humidity,
                                dissipating=False, max_intensity=100,
                                point_radius=1)
fig.add_layer(heat_layer)
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [79]:
# Narrow down cities to fit weather conditions
nice_low_temp = cities_df[cities_df["Max Temp"]>=70]
nice_high_temp = nice_low_temp[nice_low_temp["Max Temp"]<=90] 
nice_humidity = nice_high_temp[nice_high_temp["Humidity"]<=50] 
nice_cloudiness = nice_humidity[nice_humidity["Cloudiness"]<=30]
nice_weather = nice_cloudiness[nice_cloudiness["Wind Speed"]<=8]

nice_weather.dropna(how="any")

nice_weather

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
324,Aranos,-24.13,19.12,84.51,13,0,7.92,NaN,1607708548
342,Kankan,10.39,-9.31,86.43,20,0,2.68,GN,1607708571
429,Birao,10.28,22.79,81.37,24,0,5.95,CF,1607708604
438,Koutiala,12.39,-5.46,85.35,14,1,6.33,ML,1607708681
474,Malanville,11.87,3.39,83.01,17,0,3.98,BJ,1607708726
493,Tocopilla,-22.09,-70.20,70.23,48,15,6.31,CL,1607708750
509,Águilas,37.41,-1.58,71.60,46,20,6.93,ES,1607708770
545,Āsosa,10.07,34.53,72.88,29,29,5.82,ET,1607708816

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [86]:
hotel_df = nice_weather

In [87]:
hotel_df["Hotel Name"] = ''

params = {
    "radius": 5000,
    "types": "lodging",
    "key": g_key
}

# Use the lat/lng we recovered to identify airports
for index, row in hotel_df.iterrows():
    # get lat, lng from df
    lat = row["Lat"]
    lng = row["Lng"]

    # change location each iteration while leaving original params in place
    params["location"] = f"{lat},{lng}"

    # Use the search term: "International Airport" and our lat/lng
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # make request and print url
    name_address = requests.get(base_url, params=params)

    # convert to json
    name_address = name_address.json()

    # Since some data may be missing we incorporate a try-except to skip any that are missing a data point.
    try:
        hotel_df.loc[index, "Hotel Name"] = name_address["results"][0]["name"]
    except (KeyError, IndexError):
        print("Missing field/result... skipping.")
        
hotel_df

<ipython-input-87-9efac7c774ec>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hotel_df["Hotel Name"] = ''
/Users/nickcresta/opt/anaconda3/envs/PythonData/lib/python3.8/site-packages/pandas/core/indexing.py:1763: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)

Missing field/result... skipping.

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Hotel Name
324,Aranos,-24.13,19.12,84.51,13,0,7.92,NaN,1607708548,Ley-Lia Guest House
342,Kankan,10.39,-9.31,86.43,20,0,2.68,GN,1607708571,Hotel Bate
429,Birao,10.28,22.79,81.37,24,0,5.95,CF,1607708604,
438,Koutiala,12.39,-5.46,85.35,14,1,6.33,ML,1607708681,Hotel Campement Poule Verte
474,Malanville,11.87,3.39,83.01,17,0,3.98,BJ,1607708726,DEVO HOTEL
493,Tocopilla,-22.09,-70.20,70.23,48,15,6.31,CL,1607708750,Hotel Galvarino
509,Águilas,37.41,-1.58,71.60,46,20,6.93,ES,1607708770,Hotel Carlos III
545,Āsosa,10.07,34.53,72.88,29,29,5.82,ET,1607708816,Blendana Hotel Assosa

In [88]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [89]:
# Add marker layer ontop of heat map
markers = gmaps.marker_layer(locations, info_box_content=hotel_info)

# Display figure
fig.add_layer(markers)

fig

Figure(layout=FigureLayout(height='420px'))